default_config:

logger:
  default: info
  logs:
    custom_components.waste_collection_schedule: debug

# Change these config to your needs
waste_collection_schedule:
  sources:
    - name: koeflach_at
      args:
        service: Rsa
        street: Ackerweg
        mfh: False

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
